### ISSUE TITLE
图片形状支持不是很好啊？

### ISSUE THREAD

**Issue by Yalhu** [liangbizhi/js2wordcloud#2]
二次封装 非常棒。
但是图片形状支持不是很好啊。
设置中把`shape`去掉，加了`imageShape:'dog.png',`在第一行，只能看到少数几个字，形状和图片对不上。
看上去像一个`shape`。 是图片需要有什么特殊要求吗？

**Comment by anbee** [comment]
@Yalhu 请问一下，最后这个问题是怎么解决？

**Comment by liangbizhi** [comment]
@Yalhu 最好使用黑色白底的图片，即图形黑色，背景为白色

**Comment by Yalhu** [comment]
好像只有黑色的图形看起来还有点样子，其他单色都不行。
而且形状受收到 container高度的影响，产生形变
