### ISSUE TITLE
请问如何设置每个词的颜色？

### ISSUE THREAD

**Issue by anbee** [liangbizhi/js2wordcloud#4]
我有一个颜色数组，我想要数据中每一个词对应颜色数组，请问这要如何解决？

**Comment by liangbizhi** [comment]
没这个功能呢

**Comment by anbee** [comment]
感谢您的解答！
昨晚研究了一下，这应该是wordColor2.js中的问题，我后来还是直接在color的回调函数里去匹配颜色数组中包含这个value的时候返回颜色。
这个控件很棒，谢谢您的贡献！
